#pragma once

#include <vector>

namespace settings {

struct SettingItem {
    const wchar_t* name;
    const wchar_t* command;
    const wchar_t* area;
    const wchar_t* altNames;
};

inline const std::vector<SettingItem>& GetSettingsList() {
    static const std::vector<SettingItem> kSettings = {
        { L"Settings (Application homepage)", L"ms-settings:", L"Settings", L"Settings app;System settings" },
        { L"Control Panel (Application homepage)", L"control.exe", L"Control Panel", L"" },
        { L"Access work or school", L"ms-settings:workplace", L"Accounts", L"Workplace" },
        { L"Email and app accounts", L"ms-settings:emailandaccounts", L"Accounts", L"" },
        { L"Family and other people", L"ms-settings:otherusers", L"Accounts", L"Other users" },
        { L"Set up a kiosk", L"ms-settings:assignedaccess", L"Accounts", L"Assigned access" },
        { L"Sign-in options", L"ms-settings:signinoptions", L"Accounts", L"sign in;sign-in;password;pin;windows hello;fingerprint;face" },
        { L"Sign-in options - Dynamic lock", L"ms-settings:signinoptions-dynamiclock", L"Accounts", L"" },
        { L"Sync your settings", L"ms-settings:sync", L"Accounts", L"" },
        { L"Windows Hello setup - Face", L"ms-settings:signinoptions-launchfaceenrollment", L"Accounts", L"" },
        { L"Windows Hello setup - Fingerprint", L"ms-settings:signinoptions-launchfingerprintenrollment", L"Accounts", L"" },
        { L"Your info", L"ms-settings:yourinfo", L"Accounts", L"" },
        { L"Apps & Features", L"ms-settings:appsfeatures", L"Apps", L"Uninstall programs;Remove programs;Change programs;Repair programs;apps;apps & features;installed apps;uninstall;remove programs;applications" },
        { L"App features", L"ms-settings:appsfeatures-app", L"Apps", L"" },
        { L"Apps for websites", L"ms-settings:appsforwebsites", L"Apps", L"" },
        { L"Default apps", L"ms-settings:defaultapps", L"Apps", L"default apps;default browser;default programs;defaults" },
        { L"Manage optional features", L"ms-settings:optionalfeatures", L"Apps", L"" },
        { L"Offline Maps", L"ms-settings:maps", L"Apps", L"" },
        { L"Offline Maps - Download maps", L"ms-settings:maps-downloadmaps", L"Apps", L"" },
        { L"Startup apps", L"ms-settings:startupapps", L"Apps", L"startup;startup apps;autostart;run on startup" },
        { L"Video playback", L"ms-settings:videoplayback", L"Apps", L"" },
        { L"Notifications", L"ms-settings:cortana-notifications", L"Cortana", L"" },
        { L"More details", L"ms-settings:cortana-moredetails", L"Cortana", L"" },
        { L"Permissions and history", L"ms-settings:cortana-permissions", L"Cortana", L"" },
        { L"Windows search", L"ms-settings:cortana-windowssearch", L"Cortana", L"Windows search settings" },
        { L"Cortana - Language", L"ms-settings:cortana-language", L"Cortana", L"Talk" },
        { L"Cortana", L"ms-settings:cortana", L"Cortana", L"" },
        { L"Talk to Cortana", L"ms-settings:cortana-talktocortana", L"Cortana", L"" },
        { L"AutoPlay", L"ms-settings:autoplay", L"Devices", L"" },
        { L"Bluetooth and other devices", L"ms-settings:bluetooth", L"Devices", L"bluetooth;bt;wireless;pair" },
        { L"Devices", L"ms-settings:bluetooth", L"Bluetooth & devices", L"Manage devices;Add devices;Bluetooth devices;bluetooth;bt;wireless;pair" },
        { L"Bluetooth & devices", L"ms-settings:devices", L"Settings", L"Devices;Bluetooth devices;Printers and scanners;Phone Link;Camera;Mouse;Touchpad;Pen and Windows Ink;AutoPlay;USB" },
        { L"Connected Devices", L"ms-settings:connecteddevices", L"Devices", L"" },
        { L"Default camera", L"ms-settings:camera", L"Devices", L"camera;webcam" },
        { L"Mouse and touchpad", L"ms-settings:mousetouchpad", L"Devices", L"mouse;touchpad;cursor;pointer;scroll;touch" },
        { L"Pen and Windows Ink", L"ms-settings:pen", L"Devices", L"" },
        { L"Printers and scanners", L"ms-settings:printers", L"Devices", L"printers;printer;scanners;scanner;print;fax" },
        { L"Touchpad", L"ms-settings:devices-touchpad", L"Devices", L"" },
        { L"Typing", L"ms-settings:typing", L"Devices", L"typing;keyboard;autocorrect;touch keyboard" },
        { L"USB", L"ms-settings:usb", L"Devices", L"" },
        { L"Wheel", L"ms-settings:wheel", L"Devices", L"" },
        { L"Phone", L"ms-settings:mobile-devices", L"Phone", L"Mobile devices" },
        { L"Audio", L"ms-settings:easeofaccess-audio", L"Ease of access", L"Mono;Volume;Audio alerts" },
        { L"Closed captions", L"ms-settings:easeofaccess-closedcaptioning", L"Ease of access", L"" },
        { L"Color filters", L"ms-settings:easeofaccess-colorfilter", L"Ease of access", L"Inverted colors;Grayscale;Red-green;Blue-yellow;Green week;Red week;deuteranopia;protanopia;tritanopia" },
        { L"Mouse pointer", L"ms-settings:easeofaccess-mousepointer", L"Ease of access", L"Touch feedback" },
        { L"Display", L"ms-settings:easeofaccess-display", L"Ease of access", L"Transparency;Animations;Scroll bars;Size" },
        { L"Eye control", L"ms-settings:easeofaccess-eyecontrol", L"Ease of access", L"" },
        { L"Fonts", L"ms-settings:fonts", L"Ease of access", L"" },
        { L"High contrast", L"ms-settings:easeofaccess-highcontrast", L"Ease of access", L"" },
        { L"Keyboard", L"ms-settings:easeofaccess-keyboard", L"Ease of access", L"Print screen;Shortcuts;On-Screen;Keys;Scroll Lock;Caps Lock;Num Lock" },
        { L"Magnifier", L"ms-settings:easeofaccess-magnifier", L"Ease of access", L"Zoom" },
        { L"Mouse", L"ms-settings:easeofaccess-mouse", L"Ease of access", L"Keypad;Touch" },
        { L"Narrator", L"ms-settings:easeofaccess-narrator", L"Ease of access", L"" },
        { L"Other options", L"ms-settings:easeofaccess-otheroptions", L"Ease of access", L"" },
        { L"Speech", L"ms-settings:easeofaccess-speechrecognition", L"Ease of access", L"Recognition;Talk" },
        { L"Extras", L"ms-settings:extras", L"Extras", L"" },
        { L"Broadcasting", L"ms-settings:gaming-broadcasting", L"Gaming", L"" },
        { L"Game bar", L"ms-settings:gaming-gamebar", L"Gaming", L"" },
        { L"Game DVR", L"ms-settings:gaming-gamedvr", L"Gaming", L"" },
        { L"Game Mode", L"ms-settings:gaming-gamemode", L"Gaming", L"" },
        { L"Playing a game full screen", L"ms-settings:quietmomentsgame", L"Gaming", L"Quiet moments game" },
        { L"TruePlay", L"ms-settings:gaming-trueplay", L"Gaming", L"" },
        { L"Xbox Networking", L"ms-settings:gaming-xboxnetworking", L"Gaming", L"" },
        { L"Audio and speech", L"ms-settings:holographic-audio", L"Mixed reality", L"Holographic audio" },
        { L"Environment", L"ms-settings:privacy-holographic-environment", L"Mixed reality", L"Holographic Environment" },
        { L"Headset display", L"ms-settings:holographic-headset", L"Mixed reality", L"Holographic Headset" },
        { L"Uninstall", L"ms-settings:holographic-management", L"Mixed reality", L"Holographic Management" },
        { L"Airplane mode", L"ms-settings:network-airplanemode", L"Network and Internet", L"" },
        { L"Proximity", L"ms-settings:proximity", L"Network and Internet", L"" },
        { L"Cellular and SIM", L"ms-settings:network-cellular", L"Network and Internet", L"" },
        { L"Data usage", L"ms-settings:datausage", L"Network and Internet", L"" },
        { L"Dial-up", L"ms-settings:network-dialup", L"Network and Internet", L"" },
        { L"Direct access", L"ms-settings:network-directaccess", L"Network and Internet", L"" },
        { L"Ethernet", L"ms-settings:network-ethernet", L"Network and Internet", L"DNS;SDNS;SecureDNS;Gateway;DHCP;IP" },
        { L"Manage known networks", L"ms-settings:network-wifisettings", L"Network and Internet", L"Wi-Fi settings;wifi" },
        { L"Mobile hotspot", L"ms-settings:network-mobilehotspot", L"Network and Internet", L"hotspot;mobile hotspot;share internet" },
        { L"NFC", L"ms-settings:nfctransactions", L"Network and Internet", L"NFC Transactions" },
        { L"Proxy", L"ms-settings:network-proxy", L"Network and Internet", L"proxy;manual proxy;pac" },
        { L"Network status", L"ms-settings:network-status", L"Network and Internet", L"" },
        { L"Network", L"ms-settings:network", L"Network and Internet", L"DNS;SDNS;SecureDNS;Gateway;DHCP;IP;network;internet;ethernet;connection" },
        { L"VPN", L"ms-settings:network-vpn", L"Network and Internet", L"vpn;virtual private network" },
        { L"Wi-Fi", L"ms-settings:network-wifi", L"Network and Internet", L"Wireless;Metered connection;wifi;wi-fi;wlan;wireless;internet" },
        { L"Wi-Fi Calling", L"ms-settings:network-wificalling", L"Network and Internet", L"wifi" },
        { L"Background", L"ms-settings:personalization-background", L"Personalization", L"Wallpaper;Picture;Image;wallpaper;background;desktop image;picture" },
        { L"Choose which folders appear on Start", L"ms-settings:personalization-start-places", L"Personalization", L"Start places" },
        { L"Colors", L"ms-settings:colors", L"Personalization", L"Dark mode;Light mode;Dark color;Light color;App color;Taskbar color;Window border" },
        { L"Glance", L"ms-settings:personalization-glance", L"Personalization", L"" },
        { L"Lock screen", L"ms-settings:lockscreen", L"Personalization", L"Image;Picture;Screen saver;lock screen;lockscreen" },
        { L"Navigation bar", L"ms-settings:personalization-navbar", L"Personalization", L"" },
        { L"Personalization (category)", L"ms-settings:personalization", L"Settings", L"personalization;personalize;wallpaper;theme;colors" },
        { L"Start", L"ms-settings:personalization-start", L"Personalization", L"" },
        { L"Taskbar", L"ms-settings:taskbar", L"Personalization", L"taskbar;task bar;taskbar behaviors;unhide taskbar" },
        { L"Themes", L"ms-settings:themes", L"Personalization", L"themes;theme;desktop theme" },
        { L"Add your phone", L"ms-settings:mobile-devices-addphone", L"Phone", L"" },
        { L"Direct open your phone", L"ms-settings:mobile-devices-addphone-direct", L"Phone", L"" },
        { L"Accessory apps", L"ms-settings:privacy-accessoryapps", L"Privacy", L"" },
        { L"Account info", L"ms-settings:privacy-accountinfo", L"Privacy", L"" },
        { L"Activity history", L"ms-settings:privacy-activityhistory", L"Privacy", L"" },
        { L"Advertising ID", L"ms-settings:privacy-advertisingid", L"Privacy", L"" },
        { L"App diagnostics", L"ms-settings:privacy-appdiagnostics", L"Privacy", L"" },
        { L"Automatic file downloads", L"ms-settings:privacy-automaticfiledownloads", L"Privacy", L"" },
        { L"Background Apps", L"ms-settings:privacy-backgroundapps", L"Privacy", L"" },
        { L"Calendar", L"ms-settings:privacy-calendar", L"Privacy", L"" },
        { L"Call history", L"ms-settings:privacy-callhistory", L"Privacy", L"" },
        { L"Camera", L"ms-settings:privacy-webcam", L"Privacy", L"" },
        { L"Contacts", L"ms-settings:privacy-contacts", L"Privacy", L"" },
        { L"Documents", L"ms-settings:privacy-documents", L"Privacy", L"" },
        { L"Email", L"ms-settings:privacy-email", L"Privacy", L"" },
        { L"Eye tracker", L"ms-settings:privacy-eyetracker", L"Privacy", L"" },
        { L"Feedback and diagnostics", L"ms-settings:privacy-feedback", L"Privacy", L"" },
        { L"File system", L"ms-settings:privacy-broadfilesystemaccess", L"Privacy", L"" },
        { L"General", L"ms-settings:privacy-general", L"Privacy", L"" },
        { L"Inking and typing", L"ms-settings:privacy-speechtyping", L"Privacy", L"Speech typing" },
        { L"Location", L"ms-settings:privacy-location", L"Privacy", L"" },
        { L"Messaging", L"ms-settings:privacy-messaging", L"Privacy", L"" },
        { L"Microphone", L"ms-settings:privacy-microphone", L"Privacy", L"microphone;mic;record audio" },
        { L"Motion", L"ms-settings:privacy-motion", L"Privacy", L"" },
        { L"Notifications", L"ms-settings:privacy-notifications", L"Privacy", L"" },
        { L"Other devices", L"ms-settings:privacy-customdevices", L"Privacy", L"Custom devices" },
        { L"Phone calls", L"ms-settings:privacy-phonecalls", L"Privacy", L"" },
        { L"Pictures", L"ms-settings:privacy-pictures", L"Privacy", L"" },
        { L"Radios", L"ms-settings:privacy-radios", L"Privacy", L"" },
        { L"Speech", L"ms-settings:privacy-speech", L"Privacy", L"" },
        { L"Tasks", L"ms-settings:privacy-tasks", L"Privacy", L"" },
        { L"Videos", L"ms-settings:privacy-videos", L"Privacy", L"" },
        { L"Voice activation", L"ms-settings:privacy-voiceactivation", L"Privacy", L"" },
        { L"Accounts", L"ms-settings:surfacehub-accounts", L"SurfaceHub", L"" },
        { L"Session cleanup", L"ms-settings:surfacehub-sessioncleanup", L"SurfaceHub", L"" },
        { L"Team Conferencing", L"ms-settings:surfacehub-calling", L"SurfaceHub", L"calling" },
        { L"Team device management", L"ms-settings:surfacehub-devicemanagenent", L"SurfaceHub", L"" },
        { L"Welcome screen", L"ms-settings:surfacehub-welcome", L"SurfaceHub", L"" },
        { L"About", L"ms-settings:about", L"System", L"RAM;Processor;OS;ID;Edition;Version;about;system info;specs;pc specs;ram;processor;device name" },
        { L"Advanced display settings", L"ms-settings:display-advanced", L"System", L"refresh rate;hz;144hz;165hz;240hz;60hz;display refresh rate;display information;bit depth;color format;dynamic refresh rate" },
        { L"App volume and device preferences", L"ms-settings:apps-volume", L"System", L"volume mixer;app volume;individual volume;application volume;audio output per app;spatial audio;device preferences" },
        { L"Battery Saver", L"ms-settings:batterysaver", L"System", L"battery;battery saver;power saving" },
        { L"Battery Saver settings", L"ms-settings:batterysaver-settings", L"System", L"" },
        { L"Battery use", L"ms-settings:batterysaver-usagedetails", L"System", L"Battery saver usage details" },
        { L"Clipboard", L"ms-settings:clipboard", L"System", L"clipboard;clipboard history;win+v;sync clipboard;clear clipboard data" },
        { L"Display", L"ms-settings:display", L"System", L"Night light;Blue light;Warmer color;Red eye;display;screen;resolution;monitor;monitors;scale;hdr;refresh rate" },
        { L"Default Save Locations", L"ms-settings:savelocations", L"System", L"" },
        { L"Screen rotation", L"ms-settings:screenrotation", L"System", L"" },
        { L"Duplicating my display", L"ms-settings:quietmomentspresentation", L"System", L"Presentation" },
        { L"During these hours", L"ms-settings:quietmomentsscheduled", L"System", L"Scheduled" },
        { L"Encryption", L"ms-settings:deviceencryption", L"System", L"" },
        { L"Focus assist - Quiet hours", L"ms-settings:quiethours", L"System", L"" },
        { L"Focus assist - Quiet moments", L"ms-settings:quietmomentshome", L"System", L"" },
        { L"Graphics settings", L"ms-settings:display-advancedgraphics", L"System", L"graphics;graphics settings;hags;hardware-accelerated gpu scheduling;gpu preference;variable refresh rate;vrr;optimizations for windowed games;auto hdr;high performance gpu" },
        { L"Messaging", L"ms-settings:messaging", L"System", L"" },
        { L"Multitasking", L"ms-settings:multitasking", L"System", L"multitasking;snap windows;snap layouts;snap assist;title bar window shake;virtual desktops;alt tab;timeline" },
        { L"Night light settings", L"ms-settings:nightlight", L"System", L"night light;blue light filter;warm colors;color temperature;schedule night light" },
        { L"Phone - Default apps", L"ms-settings:phone-defaultapps", L"System", L"" },
        { L"Projecting to this PC", L"ms-settings:project", L"System", L"" },
        { L"Shared experience settings", L"ms-settings:crossdevice", L"System", L"Crossdevice;Nearby sharing settings;Share across devices" },
        { L"Nearby sharing settings", L"ms-settings:crossdevice", L"System", L"Crossdevice;Share across devices;Shared experience settings" },
        { L"Share across devices", L"ms-settings:crossdevice", L"System", L"Crossdevice;Nearby sharing settings;Shared experience settings" },
        { L"Tablet mode", L"ms-settings:tabletmode", L"System", L"" },
        { L"Notifications and actions", L"ms-settings:notifications", L"System", L"notifications;alerts;do not disturb;focus;focus assist;dnd;priority notifications" },
        { L"Remote Desktop", L"ms-settings:remotedesktop", L"System", L"remote desktop;enable rdp;allow remote desktop;remote desktop port" },
        { L"Phone", L"ms-settings:phone", L"System", L"" },
        { L"Power and sleep", L"ms-settings:powersleep", L"System", L"power;sleep;battery;power & sleep;energy;screen off;standby;power mode;power plan" },
        { L"Sound", L"ms-settings:sound", L"System", L"sound;audio;volume;speaker;speakers;headphones;mic;microphone;sound settings" },
        { L"Storage Sense", L"ms-settings:storagesense", L"System", L"storage;disk space;free up space;clean drive;storage sense;cleanup recommendations;temporary files" },
        { L"Storage policies", L"ms-settings:storagepolicies", L"System", L"" },
        { L"Date and time", L"ms-settings:dateandtime", L"Time and language", L"date;time;clock;timezone;time zone;set time" },
        { L"Japan IME settings", L"ms-settings:regionlanguage-jpnime", L"Time and language", L"jpnime" },
        { L"Region", L"ms-settings:regionformatting", L"Time and language", L"Region formatting" },
        { L"Keyboard", L"ms-settings:keyboard", L"Time and language", L"" },
        { L"Regional language", L"ms-settings:regionlanguage", L"Time and language", L"language;region;locale;keyboard language;input language" },
        { L"Bopomofo IME", L"ms-settings:regionlanguage-bpmfime", L"Time and language", L"bpmf" },
        { L"Cangjie IME", L"ms-settings:regionlanguage-cangjieime", L"Time and language", L"" },
        { L"Pinyin IME settings - domain lexicon", L"ms-settings:regionlanguage-chsime-pinyin-domainlexicon", L"Time and language", L"" },
        { L"Pinyin IME settings - Key configuration", L"ms-settings:regionlanguage-chsime-pinyin-keyconfig", L"Time and language", L"" },
        { L"Pinyin IME settings - UDP", L"ms-settings:regionlanguage-chsime-pinyin-udp", L"Time and language", L"" },
        { L"Wubi IME settings - UDP", L"ms-settings:regionlanguage-chsime-wubi-udp", L"Time and language", L"" },
        { L"Quickime", L"ms-settings:regionlanguage-quickime", L"Time and language", L"" },
        { L"Pinyin IME settings", L"ms-settings:regionlanguage-chsime-pinyin", L"Time and language", L"" },
        { L"Speech", L"ms-settings:speech", L"Time and language", L"" },
        { L"Wubi IME settings", L"ms-settings:regionlanguage-chsime-wubi", L"Time and language", L"" },
        { L"Activation", L"ms-settings:activation", L"Update and security", L"activation;product key;change product key;windows license;digital license;upgrade windows" },
        { L"Backup", L"ms-settings:backup", L"Update and security", L"" },
        { L"Delivery Optimization", L"ms-settings:delivery-optimization", L"Update and security", L"delivery optimization;allow downloads from other pcs;bandwidth limits;peer to peer update" },
        { L"Find My Device", L"ms-settings:findmydevice", L"Update and security", L"" },
        { L"For developers", L"ms-settings:developers", L"Update and security", L"developer mode;end task;taskbar end task;sideload apps;remote tools;developer options" },
        { L"Recovery", L"ms-settings:recovery", L"Update and security", L"recovery;reset this pc;advanced startup;uefi firmware settings;boot to bios;go back;reinstall windows;troubleshoot" },
        { L"Troubleshoot", L"ms-settings:troubleshoot", L"Update and security", L"" },
        { L"Windows Security", L"ms-settings:windowsdefender", L"Update and security", L"Windows Defender;Firewall;Virus;Core Isolation;Security Processor;Isolated Browsing;Exploit Protection;windows security;antivirus;defender;virus;threat" },
        { L"Windows Insider Program", L"ms-settings:windowsinsider", L"Update and security", L"" },
        { L"Windows Update", L"ms-settings:windowsupdate", L"Update and security", L"windows update;update;updates;patch;check for updates" },
        { L"Windows Update - Check for updates", L"ms-settings:windowsupdate-action", L"Update and security", L"" },
        { L"Windows Update - Check for updates", L"ms-settings:windowsupdate", L"Update and security", L"windows update;update;updates;patch;check for updates" },
        { L"Windows Update - Advanced options", L"ms-settings:windowsupdate-options", L"Update and security", L"windows update options;optional updates;delivery optimization;active hours;metered network update;pause updates" },
        { L"Windows Update - Restart options", L"ms-settings:windowsupdate-restartoptions", L"Update and security", L"" },
        { L"Windows Update - View update history", L"ms-settings:windowsupdate-history", L"Update and security", L"update history;view installed updates;uninstall updates;quality updates;driver updates" },
        { L"Windows Update - View optional updates", L"ms-settings:windowsupdate-optionalupdates", L"Update and security", L"" },
        { L"Workplace provisioning", L"ms-settings:workplace-provisioning", L"User accounts", L"" },
        { L"Provisioning", L"ms-settings:provisioning", L"User accounts", L"" },
        { L"Windows Anywhere", L"ms-settings:windowsanywhere", L"User accounts", L"" },
        { L"Accessibility Options", L"control access.cpl", L"Ease of access", L"access.cpl" },
        { L"Action Center", L"control /name Microsoft.ActionCenter", L"System and Security", L"wscui.cpl" },
        { L"Add Hardware", L"control /name Microsoft.AddHardware", L"Hardware and Sound", L"" },
        { L"Add or remove programs", L"control appwiz.cpl", L"Hardware and Sound", L"appwiz.cpl;Uninstall programs;Change programs;Repair programs" },
        { L"Administrative Tools", L"control /name Microsoft.AdministrativeTools", L"System and Security", L"" },
        { L"AutoPlay", L"control /name Microsoft.AutoPlay", L"Programs", L"" },
        { L"Backup and Restore", L"control /name Microsoft.BackupAndRestore", L"System and Security", L"" },
        { L"Biometric Devices", L"control /name Microsoft.BiometricDevices", L"Hardware and Sound", L"" },
        { L"BitLocker Drive Encryption", L"control /name Microsoft.BitLockerDriveEncryption", L"System and Security", L"" },
        { L"Bluetooth devices", L"control /bthprops.cpl", L"Hardware and Sound", L"" },
        { L"Color management", L"control /name Microsoft.ColorManagement", L"Appearance and Personalization", L"colorcpl.exe;color management;icc profile;icm;monitor color;color profiles;display profile" },
        { L"Credential manager", L"control /name Microsoft.CredentialManager", L"User accounts", L"Password" },
        { L"Client service for NetWare", L"control nwc.cpl", L"Programs", L"nwc.cpl" },
        { L"Date and time", L"control /name Microsoft.DateAndTime", L"Clock and Region", L"timedate.cpl;date and time;internet time;clock" },
        { L"Default location", L"control /name Microsoft.DefaultLocation", L"Clock and Region", L"" },
        { L"Default programs", L"control /name Microsoft.DefaultPrograms", L"Programs", L"" },
        { L"Device manager", L"control /name Microsoft.DeviceManager", L"Hardware and Sound", L"hdwwiz.cpl;devmgmt.msc;device manager;devices;hardware" },
        { L"Devices and printers", L"control /name Microsoft.DevicesAndPrinters", L"Hardware and Sound", L"printers;devices and printers;control printers" },
        { L"Devices and printers", L"explorer.exe shell:::{A8A91A66-3A7D-4424-8D24-04E180695C7A}", L"Hardware and Sound", L"printers;devices and printers" },
        { L"Ease of access center", L"control /name Microsoft.EaseOfAccessCenter", L"Ease of access", L"" },
        { L"Folder options", L"control /name Microsoft.FolderOptions", L"Appearance and Personalization", L"folder options;file explorer options;show hidden files" },
        { L"Fonts", L"control /name Microsoft.Fonts", L"Appearance and Personalization", L"" },
        { L"Game controllers", L"control /name Microsoft.GameControllers", L"Hardware and Sound", L"joy.cpl;game controllers;gamepad;joystick;calibrate controller" },
        { L"Get programs", L"control /name Microsoft.GetPrograms", L"Programs", L"" },
        { L"Getting started", L"control /name Microsoft.GettingStarted", L"Control Panel", L"" },
        { L"Home group", L"control /name Microsoft.HomeGroup", L"Network and Internet", L"" },
        { L"Indexing options", L"control /name Microsoft.IndexingOptions", L"System and Security", L"indexing options;search index;rebuild index" },
        { L"Infrared", L"control /name Microsoft.Infrared", L"Hardware and Sound", L"irprops.cpl" },
        { L"Internet options", L"control /name Microsoft.InternetOptions", L"Network and Internet", L"inetcpl.cpl;internet properties;proxy settings;trusted sites;certificates;tls;ssl;connections;lan settings" },
        { L"Mail - Microsoft Exchange or Windows Messaging", L"control mlcfg32.cpl", L"Network and Internet", L"mlcfg32.cpl" },
        { L"Mouse", L"control /name Microsoft.Mouse", L"Hardware and Sound", L"mouse;mouse properties;pointer speed;cursor" },
        { L"Network and sharing center", L"control /name Microsoft.NetworkAndSharingCenter", L"Network and Internet", L"network and sharing;adapter settings;network center" },
        { L"Network Connections (ncpa.cpl)", L"ncpa.cpl", L"Network and Internet", L"ncpa.cpl;network connections;change adapter settings;network adapters;network adapter properties;ethernet properties;wifi properties;ip configuration;dns properties;lan settings;network cards;network control panel" },
        { L"Network Setup Wizard", L"control netsetup.cpl", L"Network and Internet", L"netsetup.cpl" },
        { L"ODBC Data Source Administrator (32-bit)", L"%windir%/syswow64/odbcad32.exe", L"System and Security", L"odbccp32.cpl" },
        { L"ODBC Data Source Administrator (64-bit)", L"%windir%/system32/odbcad32.exe", L"System and Security", L"" },
        { L"Offline files", L"control /name Microsoft.OfflineFiles", L"Network and Internet", L"" },
        { L"Parental controls", L"control /name Microsoft.ParentalControls", L"User accounts", L"" },
        { L"Pen and input devices", L"control /name Microsoft.PenAndInputDevices", L"Hardware and Sound", L"" },
        { L"Pen and touch", L"control /name Microsoft.PenAndTouch", L"Hardware and Sound", L"" },
        { L"People Near Me", L"control /name Microsoft.PeopleNearMe", L"User accounts", L"" },
        { L"Performance information and tools", L"control /name Microsoft.PerformanceInformationAndTools", L"System and Security", L"" },
        { L"Phone and modem - Options", L"control /name Microsoft.PhoneAndModemOptions", L"Network and Internet", L"modem.cpl;telephon.cpl" },
        { L"Phone and modem", L"control /name Microsoft.PhoneAndModem", L"Network and Internet", L"modem.cpl;telephon.cpl" },
        { L"Power options", L"control /name Microsoft.PowerOptions", L"System and Security", L"powercfg.cpl" },
        { L"Printers", L"control /name Microsoft.Printers", L"Hardware and Sound", L"" },
        { L"Problem reports and solutions", L"control /name Microsoft.ProblemReportsAndSolutions", L"System and Security", L"" },
        { L"Programs and features", L"control /name Microsoft.ProgramsAndFeatures", L"Programs", L"" },
        { L"Recovery", L"control /name Microsoft.Recovery", L"System and Security", L"" },
        { L"Region and language", L"control /name Microsoft.RegionAndLanguage", L"Clock and Region", L"" },
        { L"RemoteApp and desktop connections", L"control /name Microsoft.RemoteAppAndDesktopConnections", L"Network and Internet", L"" },
        { L"Scanners and cameras", L"control /name Microsoft.ScannersAndCameras", L"Hardware and Sound", L"sticpl.cpl" },
        { L"Scheduled tasks", L"control schedtasks", L"System and Security", L"schedtasks" },
        { L"Security Center", L"control /name Microsoft.SecurityCenter", L"System and Security", L"" },
        { L"Sound", L"control /name Microsoft.Sound", L"Hardware and Sound", L"" },
        { L"Speech recognition", L"control /name Microsoft.SpeechRecognition", L"Ease of access", L"" },
        { L"Sync center", L"control /name Microsoft.SyncCenter", L"System and Security", L"" },
        { L"System", L"control sysdm.cpl", L"System and Security", L"sysdm.cpl" },
        { L"Tablet PC settings", L"control /name Microsoft.TabletPCSettings", L"System and Security", L"TabletPC.cpl" },
        { L"Text to speech", L"control /name Microsoft.TextToSpeech", L"Ease of access", L"" },
        { L"User accounts", L"control /name Microsoft.UserAccounts", L"User accounts", L"" },
        { L"Welcome center", L"control /name Microsoft.WelcomeCenter", L"System and Security", L"" },
        { L"Windows Anytime Upgrade", L"control /name Microsoft.WindowsAnytimeUpgrade", L"System and Security", L"" },
        { L"Windows CardSpace", L"control /name Microsoft.CardSpace", L"Hardware and Sound", L"" },
        { L"Windows Defender", L"control /name Microsoft.WindowsDefender", L"System and Security", L"" },
        { L"Windows Firewall", L"control /name Microsoft.WindowsFirewall", L"System and Security", L"" },
        { L"Windows Mobility Center", L"control /name Microsoft.MobilityCenter", L"Network and Internet", L"" },
        { L"Display properties", L"control Desk.cpl", L"Hardware and Sound", L"desk.cpl" },
        { L"FindFast", L"control FindFast.cpl", L"System and Security", L"findfast.cpl" },
        { L"Regional settings properties", L"control Intl.cpl", L"Ease of access", L"intl.cpl" },
        { L"Joystick properties", L"control Joy.cpl", L"Hardware and Sound", L"joy.cpl" },
        { L"Mouse, Fonts, Keyboard, and Printers properties", L"control Main.cpl", L"Hardware and Sound", L"main.cpl" },
        { L"Multimedia properties", L"control Mmsys.cpl", L"Hardware and Sound", L"mmsys.cpl" },
        { L"Network properties", L"control Netcpl.cpl", L"Network and Internet", L"netcpl.cpl" },
        { L"Password properties", L"control Password.cpl", L"User accounts", L"password.cpl" },
        { L"System properties and Add New Hardware wizard", L"control Sysdm.cpl", L"Hardware and Sound", L"sysdm.cpl" },
        { L"Desktop themes", L"control Themes.cpl", L"Appearance and Personalization", L"themes.cpl" },
        { L"Microsoft Mail Post Office", L"control Wgpocpl.cpl", L"Programs", L"wgpocpl.cpl" },
        { L"Change User Account Control settings", L"UserAccountControlSettings.exe", L"System and Security", L"UserAccountControlSettings.exe;User accounts;UAC;uac;user account control;slider;admin prompt" },
        { L"Edit the system environment variables", L"SystemPropertiesAdvanced.exe", L"System and Security", L"Edit environment variables;System variables;Env vars;System env vars;sysdm.cpl;environment variables;env;path;system variables;advanced system settings" },
        { L"Edit environment variables for your account", L"rundll32.exe sysdm.cpl,EditEnvironmentVariables", L"System and Security", L"User environment variables;User variables;Env vars;User env vars;sysdm.cpl" },
        { L"Change screen saver", L"control desk.cpl,,@screensaver", L"Control Panel", L"Turn screen saver on or off;Timeout;desk.cpl" },
        { L"Connect to a wireless display", L"ms-settings-connectabledevices:devicediscovery", L"System", L"Connect panel;Connectable devices;Connect to a wireless audio device;Device discovery" },
        { L"Microsoft Management Console", L"mmc.exe", L"Administrative Tools", L"mmc.exe" },
        { L"Authorization Manager", L"azman.msc", L"Administrative Tools", L"mmc.exe;azman.msc" },
        { L"Certificates - Current User", L"certmgr.msc", L"Administrative Tools", L"mmc.exe;certmgr.msc" },
        { L"Certificates - Local Computer", L"certlm.msc", L"Administrative Tools", L"mmc.exe;certlm.msc" },
        { L"Component Services", L"comexp.msc", L"Administrative Tools", L"mmc.exe;comexp.msc;COM-Objects" },
        { L"Computer Management", L"compmgmt.msc", L"Administrative Tools", L"mmc.exe;compmgmt.msc;System Tools;Task Scheduler;Event Viewer;Shared Folders;Network sessions;SMB;Local Users and Groups;Performance Monitor;Device manager;PNP Device;Storage;Disk Management;Create and format hard disk partitions;GPT;MBR;Services;WMI Control;Windows Management Instrumentation" },
        { L"Device manager", L"devmgmt.msc", L"Administrative Tools", L"mmc.exe;devmgmt.msc;PNP Device" },
        { L"Disk Management", L"diskmgmt.msc", L"Administrative Tools", L"mmc.exe;diskmgmt.msc;Storage;Create and format hard disk partitions;GPT;MBR" },
        { L"Event Viewer", L"eventvwr.msc", L"Administrative Tools", L"mmc.exe;eventvwr.msc" },
        { L"Local Computer Policy", L"gpedit.msc", L"Administrative Tools", L"mmc.exe;gpedit.msc;Group Policy" },
        { L"IP Security Monitor", L"mmc.exe", L"Administrative Tools", L"mmc.exe" },
        { L"IP Security Policies on Local Computer", L"mmc.exe", L"Administrative Tools", L"mmc.exe" },
        { L"Local Users and Groups", L"lusrmgr.msc", L"Administrative Tools", L"mmc.exe;lusrmgr.msc" },
        { L"Performance Monitor", L"perfmon.msc", L"Administrative Tools", L"mmc.exe;perfmon.msc" },
        { L"Print Management", L"printmanagement.msc", L"Administrative Tools", L"mmc.exe;printmanagement.msc;Printer Spooler" },
        { L"Resultant Set of Policy", L"rsop.msc", L"Administrative Tools", L"mmc.exe;rsop.msc" },
        { L"Security Configuration and Analysis", L"secpol.msc", L"Administrative Tools", L"mmc.exe;secpol.msc" },
        { L"Security Templates", L"mmc.exe", L"Administrative Tools", L"mmc.exe" },
        { L"Services", L"services.msc", L"Administrative Tools", L"mmc.exe;services.msc" },
        { L"Shared Folders", L"fsmgmt.msc", L"Administrative Tools", L"mmc.exe;fsmgmt.msc;Network sessions" },
        { L"Task Scheduler", L"taskschd.msc", L"Administrative Tools", L"mmc.exe;taskschd.msc" },
        { L"TPM Management", L"tpm.msc", L"Administrative Tools", L"mmc.exe;tpm.msc" },
        { L"Windows Defender Firewall with Advanced Security", L"wf.msc", L"Administrative Tools", L"mmc.exe;WF.msc" },
        { L"WMI Control", L"wmimgmt.msc", L"Administrative Tools", L"mmc.exe;WmiMgmt.msc;Windows Management Instrumentation" },

        // Deep Administrative Tools & Control Applets
        { L"Turn Windows features on or off", L"OptionalFeatures.exe", L"System and Security", L"OptionalFeatures.exe;windows features;optional features;hyper-v;wsl;windows subsystem for linux;iis;sandbox;windows sandbox;telnet;smb1;.net framework;tftp;virtual machine platform;features" },
        { L"System Configuration", L"msconfig.exe", L"Administrative Tools", L"msconfig.exe;msconfig;system configuration;boot options;safe mode;clean boot;services configuration;diagnostic startup;bootloader" },
        { L"Disk Cleanup", L"cleanmgr.exe", L"Administrative Tools", L"cleanmgr.exe;cleanmgr;disk cleanup;free up disk space;clean c drive;delete temp files;recycle bin cleanup;windows update cleanup" },
        { L"DirectX Diagnostic Tool", L"dxdiag.exe", L"Administrative Tools", L"dxdiag.exe;dxdiag;directx;directx diagnostic;gpu info;vram;system specifications;sound diagnostics;display diagnostics;graphics card info" },
        { L"User Accounts (Advanced)", L"netplwiz.exe", L"Administrative Tools", L"netplwiz.exe;netplwiz;control userpasswords2;userpasswords2;auto login;autologin;manage user accounts;local accounts;passwords;require sign in" },
        { L"Resource Monitor", L"resmon.exe", L"Administrative Tools", L"resmon.exe;resmon;resource monitor;cpu monitor;memory monitor;disk activity;network activity;handles;modules;processes" },
        { L"Registry Editor", L"regedit.exe", L"Administrative Tools", L"regedit.exe;regedit;registry;reg;hkey_local_machine;hkey_current_user;regedit32" },
        { L"Display Color Calibration", L"dccw.exe", L"Appearance and Personalization", L"dccw.exe;dccw;color calibration;calibrate display;gamma;color balance;brightness;contrast;calibrate monitor" },
        { L"Color Management", L"colorcpl.exe", L"Appearance and Personalization", L"colorcpl.exe;color management;icc profile;icm;monitor color;color profiles;display profile" },
        { L"Windows Memory Diagnostic", L"mdsched.exe", L"Administrative Tools", L"mdsched.exe;mdsched;memory test;ram test;check ram;memory diagnostic;ram errors" },
        { L"Sound Control Panel (Legacy)", L"mmsys.cpl", L"Hardware and Sound", L"mmsys.cpl;sound control panel;playback devices;recording devices;stereo mix;audio settings legacy;communications;sounds;exclusive mode;bitrate;sample rate" },
        { L"Internet Properties", L"inetcpl.cpl", L"Network and Internet", L"inetcpl.cpl;internet options;proxy settings;trusted sites;certificates;tls;ssl;connections;lan settings" },
        { L"Game Controllers", L"joy.cpl", L"Hardware and Sound", L"joy.cpl;game controllers;gamepad;joystick;calibrate controller;controller test;usb gamepad" },
        { L"Date and Time (Legacy)", L"timedate.cpl", L"Clock and Region", L"timedate.cpl;date and time;internet time;ntp;sync time;additional clocks;time zone" },
        { L"Region (Legacy)", L"intl.cpl", L"Clock and Region", L"intl.cpl;region;formats;short date;long date;administrative region;system locale;non-unicode" },
        { L"Power Options (Legacy)", L"powercfg.cpl", L"System and Security", L"powercfg.cpl;power options;power plan;high performance;ultimate performance;balanced;sleep timer;turn off display;choose what the power button does;fast startup" },
        { L"Programs and Features (Legacy)", L"appwiz.cpl", L"Programs", L"appwiz.cpl;uninstall a program;programs and features;classic uninstall;installed updates;view installed updates" },
        { L"System Properties (Legacy)", L"sysdm.cpl", L"System and Security", L"sysdm.cpl;system properties;computer name;hardware;device manager;advanced system settings;system protection;system restore;pagefile;virtual memory;remote" },
        { L"Windows Defender Firewall (Legacy)", L"firewall.cpl", L"System and Security", L"firewall.cpl;firewall;allow an app through firewall;inbound rules;outbound rules;turn firewall on or off;network firewall" },
        { L"Devices and Printers (Classic)", L"control printers", L"Hardware and Sound", L"control printers;printers;classic printers;devices and printers;add printer;printer properties;print queue" },
        { L"Remote Desktop Connection", L"mstsc.exe", L"System and Security", L"mstsc.exe;mstsc;remote desktop;rdp;remote connect;terminal services" },
        { L"About Windows (Winver)", L"winver.exe", L"System", L"winver.exe;winver;windows version;os build;build number;windows 11 edition" },
        { L"Performance Options", L"SystemPropertiesPerformance.exe", L"System and Security", L"SystemPropertiesPerformance.exe;performance options;visual effects;adjust for best performance;smooth edges of screen fonts;virtual memory;page file;paging file size" },
        { L"System Protection (System Restore)", L"SystemPropertiesProtection.exe", L"System and Security", L"SystemPropertiesProtection.exe;system protection;system restore;create restore point;configure restore;restore points" },
        { L"System Properties - Computer Name", L"SystemPropertiesComputerName.exe", L"System and Security", L"SystemPropertiesComputerName.exe;rename pc;workgroup;domain;full computer name" },
        { L"System Properties - Hardware", L"SystemPropertiesHardware.exe", L"Hardware and Sound", L"SystemPropertiesHardware.exe;device installation settings;hardware wizard" },
        { L"System Properties - Remote", L"SystemPropertiesRemote.exe", L"System and Security", L"SystemPropertiesRemote.exe;remote desktop;remote assistance;allow remote connections" },
        { L"Data Execution Prevention (DEP)", L"SystemPropertiesDataExecutionPrevention.exe", L"System and Security", L"SystemPropertiesDataExecutionPrevention.exe;dep;data execution prevention;turn on dep" },
        { L"God Mode (All Tasks)", L"explorer.exe shell:::{ED7BA470-8E54-465E-825C-99712043E01C}", L"Administrative Tools", L"god mode;godmode;all tasks;all settings;master control panel;every setting" },

        // Modern Windows 11 Deep Settings URIs
        { L"Core Isolation (Memory Integrity)", L"ms-settings:coreisolation", L"Update and security", L"ms-settings:coreisolation;core isolation;memory integrity;hvci;hypervisor;vbs;virtualization-based security;driver blacklist;vulnerable driver blocklist;security processor" },
        { L"Exploit Protection", L"ms-settings:exploitprotection", L"Update and security", L"ms-settings:exploitprotection;exploit protection;dep;cfg;aslr;system exploit protection;mitigations" },
        { L"Sound Devices & Properties", L"ms-settings:sound-devices", L"System", L"ms-settings:sound-devices;sound devices;output devices;input devices;default playback device;sample rate;bitrate;audio enhancement;audio properties" },
        { L"Encrypted DNS & IP Settings", L"ms-settings:network-ethernet", L"Network and Internet", L"ms-settings:network-ethernet;dns;encrypted dns;dns over https;doh;static ip;dhcp;ipv4;ipv6;gateway;subnet mask;ip address" },
        { L"Installed Apps (Windows 11)", L"ms-settings:installed-apps", L"Apps", L"ms-settings:installed-apps;installed apps;uninstall apps;remove apps;installed programs;manage apps" },
    };
    return kSettings;
}

} // namespace settings
